[accounts.disroot]
default = true
email = "z.podbielniak@disroot.org"
display-name = "Zach Podbielniak"
downloads-dir = "/var/home/zach/Downloads"
backend.type = "imap"
backend.host = "disroot.org"
backend.port = 993
backend.login = "z.podbielniak@disroot.org"
backend.encryption.type = "tls"
backend.auth.type = "password"
backend.auth.command = "pass show disroot-email"
message.send.backend.type = "smtp"
message.send.backend.host = "disroot.org"
message.send.backend.port = 587
message.send.backend.login = "z.podbielniak@disroot.org"
message.send.backend.encryption.type = "start-tls"
message.send.backend.auth.type = "password"
message.send.backend.auth.command = "pass show disroot-email"

[accounts.gmail]
default = false
email = "z.podbielniak@gmail.com"
display-name = "Zach Podbielniak"
downloads-dir = "/var/home/zach/Downloads"
backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.login = "z.podbielniak@gmail.com"
backend.encryption.type = "tls"
backend.auth.type = "password"
backend.auth.command = "pass show gmail-email"
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 465
message.send.backend.login = "z.podbielniak@gmail.com"
message.send.backend.encryption.type = "tls"
message.send.backend.auth.type = "password"
message.send.backend.auth.command = "pass show gmail-email"
