# https://yazi-rs.github.io/docs/configuration/keymap

[mgr]
append_keymap = [
    { on = ["g", "D"], run = "cd ~/.dotfiles", desc = "goto dotfiles"},
    { on = ["g", "m"], run = "cd ~/Music", desc = "goto Music"},
    { on = ["g", "n"], run = "cd ~/Documents/notes", desc = "goto notes"},
    
    { on = ["e", "v"], run = "shell --block nvim", desc = "edit with neovim"},
]
